import { DayOfWeek, MasterWeeklyTemplate, PillarType, ScheduleItemTemplate } from '../types';

export const PILLARS_CONFIG: Record<PillarType, { label: string; color: string; bgBadge: string; textBadge: string; border: string }> = {
  academics: {
    label: 'Academics',
    color: '#1E3A8A', // Deep Navy
    bgBadge: 'bg-[#EBF1F8]',
    textBadge: 'text-[#1E3A8A]',
    border: 'border-[#BFDBFE]',
  },
  health: {
    label: 'Health',
    color: '#166534', // Forest Sage
    bgBadge: 'bg-[#ECFDF5]',
    textBadge: 'text-[#166534]',
    border: 'border-[#BBF7D0]',
  },
  skills: {
    label: 'Skills',
    color: '#B45309', // Ochre / Amber
    bgBadge: 'bg-[#FEF3C7]',
    textBadge: 'text-[#92400E]',
    border: 'border-[#FDE68A]',
  },
  observation: {
    label: 'Observation',
    color: '#6D28D9', // Deep Violet
    bgBadge: 'bg-[#F3E8FF]',
    textBadge: 'text-[#6D28D9]',
    border: 'border-[#DDD6FE]',
  },
  entrepreneurship: {
    label: 'Entrepreneurship',
    color: '#0F766E', // Deep Teal
    bgBadge: 'bg-[#F0FDFA]',
    textBadge: 'text-[#0F766E]',
    border: 'border-[#99F6E4]',
  },
  review: {
    label: 'Review',
    color: '#C2410C', // Rust / Terracotta
    bgBadge: 'bg-[#FFF7ED]',
    textBadge: 'text-[#C2410C]',
    border: 'border-[#FFEDD5]',
  },
};

export const FITNESS_SCHEDULE: Record<DayOfWeek, { title: string; focus: string; guidance: string }> = {
  Monday: {
    title: 'Easy Run + Push',
    focus: 'Aerobic base + Push mechanics',
    guidance: 'Easy progressive pace run; controlled push-up sets without training to failure.',
  },
  Tuesday: {
    title: 'Strength — Pull + Legs',
    focus: 'Pull volume + Lower body mechanics',
    guidance: 'Controlled pull-ups / rows and bodyweight/weighted squats & lunges.',
  },
  Wednesday: {
    title: 'Easy / Moderate Run + Core',
    focus: 'Aerobic continuity + Trunk stability',
    guidance: 'Mid-distance steady run; core holds, planks, and anti-rotation.',
  },
  Thursday: {
    title: 'Strength — Push + Legs',
    focus: 'Push strength + Posterior chain',
    guidance: 'Dips, push variations, hinges, and single-leg stability.',
  },
  Friday: {
    title: 'Quality Running / Intervals + Light Upper',
    focus: 'Pacing intervals + Active recovery upper',
    guidance: 'Interval pacing blocks with controlled cadence and light mobility.',
  },
  Saturday: {
    title: 'Longer Easy Aerobic + Calisthenics',
    focus: 'Endurance volume + Body control',
    guidance: 'Extended conversational pace cardio followed by calisthenics flow.',
  },
  Sunday: {
    title: 'Recovery Walk + Light Mobility',
    focus: 'Active recovery + Joint decompression',
    guidance: 'Gentle outdoor walk, diaphragmatic breathing, and hip/spine mobility.',
  },
};

export const SKILL_ROTATION: Record<DayOfWeek, { type: 'english' | 'business' | 'open'; title: string; protocol: string[] }> = {
  Monday: {
    type: 'english',
    title: 'English Fluency & Articulation',
    protocol: [
      '15 min: Vocabulary & contextual grammar',
      '20 min: Active verbal speaking aloud',
      '15 min: AI interactive conversation & corrections',
      '10 min: Deliberate repetition of corrected sentences',
    ],
  },
  Tuesday: {
    type: 'business',
    title: 'Business Intelligence & Strategy (1-1-1 Rule)',
    protocol: [
      'Focus: Business models, founder breakdowns & pharmaceutical industry economics',
      '1 Idea learned: Core commercial concept',
      '1 Thing questioned: Critical friction or assumption challenged',
      '1 Thing applicable: Actionable takeaway for ventures',
    ],
  },
  Wednesday: {
    type: 'english',
    title: 'English Fluency & Articulation',
    protocol: [
      '15 min: Vocabulary & contextual grammar',
      '20 min: Active verbal speaking aloud',
      '15 min: AI interactive conversation & corrections',
      '10 min: Deliberate repetition of corrected sentences',
    ],
  },
  Thursday: {
    type: 'business',
    title: 'Business Intelligence & Strategy (1-1-1 Rule)',
    protocol: [
      'Focus: Market structures, distribution channels & human consumer behavior',
      '1 Idea learned: Market mechanism',
      '1 Thing questioned: Competitive dynamic or vulnerability',
      '1 Thing applicable: Commercial opportunity or synthesis',
    ],
  },
  Friday: {
    type: 'english',
    title: 'English Fluency & Articulation',
    protocol: [
      '15 min: Vocabulary & contextual grammar',
      '20 min: Active verbal speaking aloud',
      '15 min: AI interactive conversation & corrections',
      '10 min: Deliberate repetition of corrected sentences',
    ],
  },
  Saturday: {
    type: 'business',
    title: 'Business Intelligence & Strategy (1-1-1 Rule)',
    protocol: [
      'Focus: Sales, unit economics, tech distribution & scale models',
      '1 Idea learned: Scale or financial lever',
      '1 Thing questioned: Unit economics risk',
      '1 Thing applicable: Integration into Sunday experiment',
    ],
  },
  Sunday: {
    type: 'open',
    title: 'Open Skill / Venture / World Awareness',
    protocol: [
      'Focus: Entrepreneurial skill, technical tools, or global awareness synthesis',
      'Direct application to weekly venture prototype or World Scan insights',
    ],
  },
};

export const SUBJECT_ROTATION: Record<DayOfWeek, { morningRevision: string; nightDeepWork: string }> = {
  Monday: {
    morningRevision: 'Pharmaceutical Chemistry Revision',
    nightDeepWork: 'Pharmaceutics (Primary Deep Work)',
  },
  Tuesday: {
    morningRevision: 'Pharmaceutics Revision',
    nightDeepWork: 'Pharmaceutical Engineering (Primary Deep Work)',
  },
  Wednesday: {
    morningRevision: 'Pharmaceutical Engineering Revision',
    nightDeepWork: 'Microbiology (Primary Deep Work)',
  },
  Thursday: {
    morningRevision: 'Microbiology Revision',
    nightDeepWork: 'Pharmaceutical Chemistry (Primary Deep Work)',
  },
  Friday: {
    morningRevision: 'Pharmaceutical Chemistry Revision',
    nightDeepWork: 'Pharmaceutical Engineering (Primary Deep Work)',
  },
  Saturday: {
    morningRevision: 'Pharmaceutical Engineering Revision',
    nightDeepWork: 'Academic Weekly Balancing (Pharmaceutics / Microbiology / PYQs)',
  },
  Sunday: {
    morningRevision: 'Weekend Revision — Subject 1 & 2',
    nightDeepWork: 'Weekend Revision — Subject 3 & 4 + Weekly Academic Prep',
  },
};

export interface DayFocusInfo {
  weekday: DayOfWeek;
  focusTitle: string; // e.g. "Microbiology AM · Chemistry PM · Business"
  morningAcademic: string;
  nightAcademic: string;
  skillOrBusiness: string;
  summary: string;
}

export const DAY_FOCUS_CONFIG: Record<DayOfWeek, DayFocusInfo> = {
  Monday: {
    weekday: 'Monday',
    focusTitle: 'Chemistry AM · Pharmaceutics PM · English',
    morningAcademic: 'Pharmaceutical Chemistry Revision',
    nightAcademic: 'Pharmaceutics (Primary Deep Work)',
    skillOrBusiness: 'English Fluency & Articulation',
    summary: 'Active recall in Chemistry, deep work in Pharmaceutics, and structured English speaking drills.',
  },
  Tuesday: {
    weekday: 'Tuesday',
    focusTitle: 'Pharmaceutics AM · Pharmaceutical Engineering PM · Business',
    morningAcademic: 'Pharmaceutics Revision',
    nightAcademic: 'Pharmaceutical Engineering (Primary Deep Work)',
    skillOrBusiness: 'Business Strategy (1-1-1 Rule)',
    summary: 'Tuesday Library Day with focused engineering deep work and 1-1-1 business model analysis.',
  },
  Wednesday: {
    weekday: 'Wednesday',
    focusTitle: 'Pharmaceutical Engineering AM · Microbiology PM · English',
    morningAcademic: 'Pharmaceutical Engineering Revision',
    nightAcademic: 'Microbiology (Primary Deep Work)',
    skillOrBusiness: 'English Fluency & Articulation',
    summary: 'Practical Knowledge Session, microbiology deep study, and structured English dialogue practice.',
  },
  Thursday: {
    weekday: 'Thursday',
    focusTitle: 'Microbiology AM · Chemistry PM · Business',
    morningAcademic: 'Microbiology Revision',
    nightAcademic: 'Pharmaceutical Chemistry (Primary Deep Work)',
    skillOrBusiness: 'Business Strategy (1-1-1 Rule)',
    summary: 'Microbiology active recall, evening Chemistry problem sets, and distribution business analysis.',
  },
  Friday: {
    weekday: 'Friday',
    focusTitle: 'Chemistry AM · Pharmaceutical Engineering PM · English',
    morningAcademic: 'Pharmaceutical Chemistry Revision',
    nightAcademic: 'Pharmaceutical Engineering (Primary Deep Work)',
    skillOrBusiness: 'English Fluency & Articulation',
    summary: 'Friday Library Day with high-yield engineering problem sets and English speech fluency.',
  },
  Saturday: {
    weekday: 'Saturday',
    focusTitle: 'Weekly balancing · Entrepreneurship · Business',
    morningAcademic: 'Academic Weekly Balancing (Pharmaceutics/Microbiology)',
    nightAcademic: 'Past Year Exam Questions & Academic Retention',
    skillOrBusiness: 'Deep Business Case Study & Saturday Weekly Reset',
    summary: 'Entrepreneurship research blocks, subject balancing, and the weekly diagnostic reset.',
  },
  Sunday: {
    weekday: 'Sunday',
    focusTitle: 'Recovery · World Scan · Build/Experiment',
    morningAcademic: 'Weekend Revision Modules 1 & 2',
    nightAcademic: 'Weekend Revision Modules 3 & 4 + Weekly Prep',
    skillOrBusiness: 'World Scan Synthesis & Prototype Testing',
    summary: 'Restorative active recovery, 90-minute global world scan, and open venture prototyping.',
  },
};

/**
 * Standard Weekday Base Template (Mon-Fri)
 */
function createStandardWeekdayTemplate(
  day: DayOfWeek,
  morningRevisionSubject: string,
  nightStudySubject: string,
  skillType: 'english' | 'business',
  specialAfternoon?: { timeRange: string; title: string; subtitle: string; protocolType: 'library' | 'flexible' }
): ScheduleItemTemplate[] {
  const fitness = FITNESS_SCHEDULE[day];

  const items: ScheduleItemTemplate[] = [
    {
      id: `${day.toLowerCase()}-1`,
      startTime: '05:00',
      endTime: '05:15',
      timeRange: '5:00–5:15 AM',
      title: 'Wake + Washroom',
      subtitle: 'Hydration, hygiene & physiological awakening',
      pillar: 'health',
      isFixed: true,
      essentialInMinDay: true,
    },
    {
      id: `${day.toLowerCase()}-2`,
      startTime: '05:15',
      endTime: '06:00',
      timeRange: '5:15–6:00 AM',
      title: `Exercise: ${fitness.title}`,
      subtitle: fitness.focus,
      pillar: 'health',
      protocolType: 'fitness',
      essentialInMinDay: true,
      notes: fitness.guidance,
    },
    {
      id: `${day.toLowerCase()}-3`,
      startTime: '06:00',
      endTime: '06:15',
      timeRange: '6:00–6:15 AM',
      title: 'Meditation / Breathing / Mental Reset',
      subtitle: 'Diaphragmatic breathing, calm focus & daily intention',
      pillar: 'health',
      essentialInMinDay: true,
    },
    {
      id: `${day.toLowerCase()}-4`,
      startTime: '06:15',
      endTime: '07:00',
      timeRange: '6:15–7:00 AM',
      title: `Secondary-Subject Revision: ${morningRevisionSubject}`,
      subtitle: 'Active recall, formula retention & high-yield flashcards',
      pillar: 'academics',
      protocolType: 'revision',
      essentialInMinDay: true,
    },
    {
      id: `${day.toLowerCase()}-5`,
      startTime: '07:00',
      endTime: '08:00',
      timeRange: '7:00–8:00 AM',
      title: 'Household Responsibility',
      subtitle: 'Domestic duties, family support & discipline',
      pillar: 'health',
      isFixed: true,
      essentialInMinDay: true,
    },
    {
      id: `${day.toLowerCase()}-6`,
      startTime: '08:00',
      endTime: '08:30',
      timeRange: '8:00–8:30 AM',
      title: 'Bath + Personal Preparation',
      subtitle: 'Grooming, nutrition & transition to work mode',
      pillar: 'health',
      isFixed: true,
      essentialInMinDay: true,
    },
    {
      id: `${day.toLowerCase()}-7`,
      startTime: '08:30',
      endTime: '10:00',
      timeRange: '8:30–10:00 AM',
      title: day === 'Wednesday' ? 'Flexible Window + Practical Knowledge Session' : 'Flexible High-Value Window',
      subtitle: day === 'Wednesday' 
        ? 'Adaptive capacity (Academics / Skills / Recovery) + 30m Practical Knowledge'
        : 'Adaptive capacity: Academics pending → Skill → PYQs → Business Research → Recovery',
      pillar: 'academics',
      protocolType: day === 'Wednesday' ? 'practical_knowledge' : 'flexible',
      essentialInMinDay: false,
    },
    {
      id: `${day.toLowerCase()}-8`,
      startTime: '10:00',
      endTime: '10:30',
      timeRange: '10:00–10:30 AM',
      title: 'Transit to College',
      subtitle: 'Commute, mental pacing & observation',
      pillar: 'academics',
      isFixed: true,
      essentialInMinDay: true,
    },
    {
      id: `${day.toLowerCase()}-9`,
      startTime: '10:30',
      endTime: '17:30',
      timeRange: '10:30 AM–5:30 PM',
      title: 'College Lectures & Academic Laboratory',
      subtitle: specialAfternoon ? specialAfternoon.subtitle : 'Core pharmaceutical curriculum, practicals & academic engagements',
      pillar: 'academics',
      protocolType: specialAfternoon ? specialAfternoon.protocolType : 'college',
      isFixed: true,
      essentialInMinDay: true,
      notes: specialAfternoon ? specialAfternoon.title : undefined,
    },
    {
      id: `${day.toLowerCase()}-10`,
      startTime: '17:30',
      endTime: '18:00',
      timeRange: '5:30–6:00 PM',
      title: 'Travel Home & Decompression',
      subtitle: 'Transit & physiological shift into evening focus',
      pillar: 'health',
      isFixed: true,
      essentialInMinDay: true,
    },
    {
      id: `${day.toLowerCase()}-11`,
      startTime: '18:00',
      endTime: '19:00',
      timeRange: '6:00–7:00 PM',
      title: skillType === 'english' ? 'Skill Development: English Fluency & Articulation' : 'Skill Development: Business Strategy (1-1-1 Rule)',
      subtitle: skillType === 'english' ? '15m Vocab → 20m Speaking → 15m AI Conversation → 10m Repetition' : '1 Idea learned → 1 Thing questioned → 1 Thing applicable',
      pillar: 'skills',
      protocolType: 'skill',
      essentialInMinDay: false,
    },
    {
      id: `${day.toLowerCase()}-12`,
      startTime: '19:00',
      endTime: '20:00',
      timeRange: '7:00–8:00 PM',
      title: 'Dinner + Household Responsibilities',
      subtitle: 'Nutrition, family connection & WhatsApp check window',
      pillar: 'health',
      isFixed: true,
      essentialInMinDay: true,
    },
    {
      id: `${day.toLowerCase()}-13`,
      startTime: '20:00',
      endTime: '23:00',
      timeRange: '8:00–11:00 PM',
      title: `Primary Subject Deep Work: ${nightStudySubject}`,
      subtitle: '8:00–9:20 Deep Study → 9:20–9:30 Break → 9:30–10:30 Notes → 10:30–11:00 Active Recall / PYQs',
      pillar: 'academics',
      protocolType: 'night_study',
      essentialInMinDay: true,
    },
    {
      id: `${day.toLowerCase()}-14`,
      startTime: '23:00',
      endTime: '23:05',
      timeRange: '11:00–11:05 PM',
      title: '5-Minute Idea Capture',
      subtitle: 'Problem observed → Target audience → Current solution → Imperfection → Potential venture',
      pillar: 'observation',
      protocolType: 'idea_capture',
      essentialInMinDay: false,
    },
    {
      id: `${day.toLowerCase()}-15`,
      startTime: '23:05',
      endTime: '23:30',
      timeRange: '11:05–11:30 PM',
      title: 'Shutdown + WhatsApp + Tomorrow Preparation',
      subtitle: 'Scorecard audit, evening closure, phone quarantine & sleep setup',
      pillar: 'review',
      protocolType: 'shutdown',
      essentialInMinDay: true,
    },
    {
      id: `${day.toLowerCase()}-16`,
      startTime: '23:30',
      endTime: '05:00',
      timeRange: '11:30 PM–5:00 AM',
      title: 'Restorative Sleep',
      subtitle: 'Non-negotiable recovery & neural consolidation',
      pillar: 'health',
      isFixed: true,
      essentialInMinDay: true,
    },
  ];

  return items;
}

/**
 * Saturday Specific Template
 */
function createSaturdayTemplate(): ScheduleItemTemplate[] {
  return [
    {
      id: 'sat-1',
      startTime: '05:00',
      endTime: '05:15',
      timeRange: '5:00–5:15 AM',
      title: 'Wake + Washroom',
      subtitle: 'Hydration & physiological awakening',
      pillar: 'health',
      isFixed: true,
      essentialInMinDay: true,
    },
    {
      id: 'sat-2',
      startTime: '05:15',
      endTime: '06:00',
      timeRange: '5:15–6:00 AM',
      title: 'Exercise: Longer Easy Aerobic + Calisthenics',
      subtitle: 'Endurance volume & calisthenics flow',
      pillar: 'health',
      protocolType: 'fitness',
      essentialInMinDay: true,
    },
    {
      id: 'sat-3',
      startTime: '06:00',
      endTime: '06:15',
      timeRange: '6:00–6:15 AM',
      title: 'Meditation / Breathing / Reset',
      subtitle: 'Mental composure & morning focus',
      pillar: 'health',
      essentialInMinDay: true,
    },
    {
      id: 'sat-4',
      startTime: '06:15',
      endTime: '07:00',
      timeRange: '6:15–7:00 AM',
      title: 'Secondary-Subject Revision: Pharm Engineering',
      subtitle: 'Active recall & high-yield revision',
      pillar: 'academics',
      protocolType: 'revision',
      essentialInMinDay: true,
    },
    {
      id: 'sat-5',
      startTime: '07:00',
      endTime: '08:00',
      timeRange: '7:00–8:00 AM',
      title: 'Household Responsibility',
      subtitle: 'Domestic duties & discipline',
      pillar: 'health',
      isFixed: true,
      essentialInMinDay: true,
    },
    {
      id: 'sat-6',
      startTime: '08:00',
      endTime: '08:30',
      timeRange: '8:00–8:30 AM',
      title: 'Bath + Preparation',
      subtitle: 'Transition to morning session',
      pillar: 'health',
      essentialInMinDay: true,
    },
    {
      id: 'sat-7',
      startTime: '08:30',
      endTime: '11:30',
      timeRange: '8:30–11:30 AM',
      title: 'College / Saturday Academic Block',
      subtitle: 'Academic classes, labs or scheduled Saturday duties',
      pillar: 'academics',
      protocolType: 'college',
      essentialInMinDay: true,
    },
    {
      id: 'sat-8',
      startTime: '11:30',
      endTime: '12:00',
      timeRange: '11:30 AM–12:00 PM',
      title: 'Lunch / Transition Home',
      subtitle: 'Nourishment and return from college',
      pillar: 'health',
      isFixed: true,
      essentialInMinDay: true,
    },
    {
      id: 'sat-9',
      startTime: '12:00',
      endTime: '13:00',
      timeRange: '12:00–1:00 PM',
      title: 'Rest / Personal Downtime',
      subtitle: 'Midday recharge & cognitive recovery',
      pillar: 'health',
      essentialInMinDay: true,
    },
    {
      id: 'sat-10',
      startTime: '13:00',
      endTime: '14:30',
      timeRange: '1:00–2:30 PM',
      title: 'Entrepreneurship Research & Analysis',
      subtitle: 'Market opportunities, pharmaceutical business models & startup thesis',
      pillar: 'entrepreneurship',
      protocolType: 'general',
      essentialInMinDay: false,
    },
    {
      id: 'sat-11',
      startTime: '14:30',
      endTime: '14:45',
      timeRange: '2:30–2:45 PM',
      title: 'Short Break & Movement',
      subtitle: 'Decompress & stretch',
      pillar: 'health',
      essentialInMinDay: false,
    },
    {
      id: 'sat-12',
      startTime: '14:45',
      endTime: '16:00',
      timeRange: '2:45–4:00 PM',
      title: 'Business / Company / Industry Analysis',
      subtitle: 'Deep-dive case study into healthcare distribution, tech & economics',
      pillar: 'entrepreneurship',
      protocolType: 'general',
      essentialInMinDay: false,
    },
    {
      id: 'sat-13',
      startTime: '16:00',
      endTime: '17:00',
      timeRange: '4:00–5:00 PM',
      title: 'Free Time / Social / Recovery',
      subtitle: 'Unstructured time, recreation & mental decompression',
      pillar: 'health',
      essentialInMinDay: false,
    },
    {
      id: 'sat-14',
      startTime: '17:00',
      endTime: '18:00',
      timeRange: '5:00–6:00 PM',
      title: 'Academic Weekly Balancing',
      subtitle: 'Resolve weakest subject backlog / PYQ focus (Pharmaceutics / Microbiology)',
      pillar: 'academics',
      protocolType: 'revision',
      essentialInMinDay: true,
    },
    {
      id: 'sat-15',
      startTime: '18:00',
      endTime: '19:00',
      timeRange: '6:00–7:00 PM',
      title: 'Business Skill Session (1-1-1 Rule)',
      subtitle: '1 Idea learned, 1 Thing questioned, 1 Thing applicable',
      pillar: 'skills',
      protocolType: 'skill',
      essentialInMinDay: false,
    },
    {
      id: 'sat-16',
      startTime: '19:00',
      endTime: '20:00',
      timeRange: '7:00–8:00 PM',
      title: 'Dinner + Household Work',
      subtitle: 'Nutrition & family time',
      pillar: 'health',
      isFixed: true,
      essentialInMinDay: true,
    },
    {
      id: 'sat-17',
      startTime: '20:00',
      endTime: '21:30',
      timeRange: '8:00–9:30 PM',
      title: 'Academic Revision / PYQs',
      subtitle: 'Past year exam questions & active recall testing',
      pillar: 'academics',
      protocolType: 'revision',
      essentialInMinDay: true,
    },
    {
      id: 'sat-18',
      startTime: '21:30',
      endTime: '22:30',
      timeRange: '9:30–10:30 PM',
      title: 'Saturday Weekly Reset',
      subtitle: '7-question diagnostic audit, consistency score & ONE key improvement',
      pillar: 'review',
      protocolType: 'weekly_reset',
      essentialInMinDay: true,
    },
    {
      id: 'sat-19',
      startTime: '22:30',
      endTime: '23:00',
      timeRange: '10:30–11:00 PM',
      title: 'Free Time / Prepare Tomorrow',
      subtitle: 'Wind down and Sunday setup',
      pillar: 'health',
      essentialInMinDay: false,
    },
    {
      id: 'sat-20',
      startTime: '23:00',
      endTime: '23:30',
      timeRange: '11:00–11:30 PM',
      title: 'Shutdown & Digital Boundary Closure',
      subtitle: 'Scorecard finalize, phone off & bedtime routine',
      pillar: 'review',
      protocolType: 'shutdown',
      essentialInMinDay: true,
    },
    {
      id: 'sat-21',
      startTime: '23:30',
      endTime: '05:00',
      timeRange: '11:30 PM–5:00 AM',
      title: 'Restorative Sleep',
      subtitle: 'Recovery & cognitive consolidation',
      pillar: 'health',
      isFixed: true,
      essentialInMinDay: true,
    },
  ];
}

/**
 * Sunday Specific Template
 */
function createSundayTemplate(): ScheduleItemTemplate[] {
  return [
    {
      id: 'sun-1',
      startTime: '05:00',
      endTime: '05:15',
      timeRange: '5:00–5:15 AM',
      title: 'Wake + Washroom',
      subtitle: 'Gentle wakeup & hydration',
      pillar: 'health',
      isFixed: true,
      essentialInMinDay: true,
    },
    {
      id: 'sun-2',
      startTime: '05:15',
      endTime: '05:45',
      timeRange: '5:15–5:45 AM',
      title: 'Exercise: Light Recovery Walk',
      subtitle: 'Outdoor movement & fresh air',
      pillar: 'health',
      protocolType: 'fitness',
      essentialInMinDay: true,
    },
    {
      id: 'sun-3',
      startTime: '05:45',
      endTime: '06:00',
      timeRange: '5:45–6:00 AM',
      title: 'Breathing / Meditation',
      subtitle: 'Deep mental calm & presence',
      pillar: 'health',
      essentialInMinDay: true,
    },
    {
      id: 'sun-4',
      startTime: '06:00',
      endTime: '07:00',
      timeRange: '6:00–7:00 AM',
      title: 'Weekend Revision — Subject 1 (Chemistry)',
      subtitle: 'Comprehensive module review & flashcard recall',
      pillar: 'academics',
      protocolType: 'revision',
      essentialInMinDay: true,
    },
    {
      id: 'sun-5',
      startTime: '07:00',
      endTime: '08:00',
      timeRange: '7:00–8:00 AM',
      title: 'Household Responsibility',
      subtitle: 'Family support & household duties',
      pillar: 'health',
      isFixed: true,
      essentialInMinDay: true,
    },
    {
      id: 'sun-6',
      startTime: '08:00',
      endTime: '08:30',
      timeRange: '8:00–8:30 AM',
      title: 'Bath + Morning Preparation',
      subtitle: 'Personal care & transition',
      pillar: 'health',
      essentialInMinDay: true,
    },
    {
      id: 'sun-7',
      startTime: '08:30',
      endTime: '09:30',
      timeRange: '8:30–9:30 AM',
      title: 'Weekend Revision — Subject 2 (Pharmaceutics)',
      subtitle: 'Core theory & formula retention',
      pillar: 'academics',
      protocolType: 'revision',
      essentialInMinDay: true,
    },
    {
      id: 'sun-8',
      startTime: '10:00',
      endTime: '11:30',
      timeRange: '10:00–11:30 AM',
      title: 'Sunday World Scan',
      subtitle: 'Global developments (15m) → Tech innovation (20m) → Industry analysis (20m) → LinkedIn/trends (15m)',
      pillar: 'observation',
      protocolType: 'world_scan',
      essentialInMinDay: false,
    },
    {
      id: 'sun-9',
      startTime: '11:30',
      endTime: '12:00',
      timeRange: '11:30 AM–12:00 PM',
      title: 'World Scan Synthesis & Write-up',
      subtitle: 'Biggest change, tech to watch, business models & venture opportunity',
      pillar: 'observation',
      protocolType: 'world_scan',
      essentialInMinDay: false,
    },
    {
      id: 'sun-10',
      startTime: '12:00',
      endTime: '15:00',
      timeRange: '12:00–3:00 PM',
      title: 'Family / Recreation / Genuine Free Time',
      subtitle: 'Uninterrupted relational connection, lunch & recreation',
      pillar: 'health',
      isFixed: true,
      essentialInMinDay: true,
    },
    {
      id: 'sun-11',
      startTime: '15:00',
      endTime: '16:30',
      timeRange: '3:00–4:30 PM',
      title: 'Entrepreneurship — Build / Experiment',
      subtitle: 'Prototype, landing page, customer research or business execution',
      pillar: 'entrepreneurship',
      protocolType: 'general',
      essentialInMinDay: false,
    },
    {
      id: 'sun-12',
      startTime: '16:30',
      endTime: '18:00',
      timeRange: '4:30–6:00 PM',
      title: 'Recovery / Social / Recreation',
      subtitle: 'Sports, outdoor time, friends & mental unwinding',
      pillar: 'health',
      essentialInMinDay: false,
    },
    {
      id: 'sun-13',
      startTime: '18:00',
      endTime: '19:00',
      timeRange: '6:00–7:00 PM',
      title: 'Open Skill / Venture / World Awareness',
      subtitle: 'Cross-disciplinary synthesis & tactical skill practice',
      pillar: 'skills',
      protocolType: 'skill',
      essentialInMinDay: false,
    },
    {
      id: 'sun-14',
      startTime: '19:00',
      endTime: '20:00',
      timeRange: '7:00–8:00 PM',
      title: 'Dinner + Household Work',
      subtitle: 'Nutrition, family connection & evening closure',
      pillar: 'health',
      isFixed: true,
      essentialInMinDay: true,
    },
    {
      id: 'sun-15',
      startTime: '20:00',
      endTime: '21:00',
      timeRange: '8:00–9:00 PM',
      title: 'Weekend Revision — Subject 3 (Pharm Engineering)',
      subtitle: 'Unit operations, calculations & conceptual mastery',
      pillar: 'academics',
      protocolType: 'revision',
      essentialInMinDay: true,
    },
    {
      id: 'sun-16',
      startTime: '21:00',
      endTime: '21:45',
      timeRange: '9:00–9:45 PM',
      title: 'Weekend Revision — Subject 4 (Microbiology)',
      subtitle: 'Microbial genetics, aseptic protocols & pharmacology links',
      pillar: 'academics',
      protocolType: 'revision',
      essentialInMinDay: true,
    },
    {
      id: 'sun-17',
      startTime: '21:45',
      endTime: '20:15',
      timeRange: '9:45–10:15 PM',
      title: 'Weekly Academic Preparation',
      subtitle: 'Review coming week syllabus, materials & laboratory schedules',
      pillar: 'academics',
      protocolType: 'revision',
      essentialInMinDay: true,
    },
    {
      id: 'sun-18',
      startTime: '22:15',
      endTime: '23:00',
      timeRange: '10:15–11:00 PM',
      title: 'Free / Recovery / Quiet Reading',
      subtitle: 'Calm evening leisure without digital stimulation',
      pillar: 'health',
      essentialInMinDay: false,
    },
    {
      id: 'sun-19',
      startTime: '23:00',
      endTime: '23:30',
      timeRange: '11:00–11:30 PM',
      title: 'Shutdown + WhatsApp + Sleep Preparation',
      subtitle: 'Final scorecard verification & restorative sleep boundary',
      pillar: 'review',
      protocolType: 'shutdown',
      essentialInMinDay: true,
    },
    {
      id: 'sun-20',
      startTime: '23:30',
      endTime: '05:00',
      timeRange: '11:30 PM–5:00 AM',
      title: 'Restorative Sleep',
      subtitle: 'Recharge for the upcoming week',
      pillar: 'health',
      isFixed: true,
      essentialInMinDay: true,
    },
  ];
}

export const INITIAL_MASTER_TEMPLATES: MasterWeeklyTemplate = {
  Monday: createStandardWeekdayTemplate(
    'Monday',
    'Pharmaceutical Chemistry Revision',
    'Pharmaceutics',
    'english'
  ),
  Tuesday: createStandardWeekdayTemplate(
    'Tuesday',
    'Pharmaceutics Revision',
    'Pharmaceutical Engineering',
    'business',
    {
      timeRange: '2:00–5:00 PM',
      title: 'Tuesday Library Day',
      subtitle: '2:00–3:15 Pending work → 3:25–4:25 Difficult topic/assignment → 4:25–5:00 Backlog clearance',
      protocolType: 'library',
    }
  ),
  Wednesday: createStandardWeekdayTemplate(
    'Wednesday',
    'Pharmaceutical Engineering Revision',
    'Microbiology',
    'english'
  ),
  Thursday: createStandardWeekdayTemplate(
    'Thursday',
    'Microbiology Revision',
    'Pharmaceutical Chemistry',
    'business',
    {
      timeRange: 'Flexible Afternoon Library',
      title: 'Thursday Flexible Library Hour',
      subtitle: 'Urgent academic backlog clearance OR Pharma industry / business model research',
      protocolType: 'flexible',
    }
  ),
  Friday: createStandardWeekdayTemplate(
    'Friday',
    'Pharmaceutical Chemistry Revision',
    'Pharmaceutical Engineering',
    'english'
  ),
  Saturday: createSaturdayTemplate(),
  Sunday: createSundayTemplate(),
};

export const PRIORITY_COLLISION_RULES = [
  { rank: 1, name: 'Academics', note: 'Non-negotiable degree foundation & core deep work' },
  { rank: 2, name: 'Health', note: 'Sleep (7+ hrs), physical movement, nutrition, mental composure' },
  { rank: 3, name: 'Skills', note: 'English fluency, communication & commercial intelligence' },
  { rank: 4, name: 'Entrepreneurship', note: 'Observation, venture prototypes & Sunday World Scan' },
  { rank: 5, name: 'Family / Social', note: 'Household duty, family meals & scheduled weekends' },
  { rank: 6, name: 'Entertainment', note: 'Controlled downtime without algorithm dopamine loops' },
];
